<a href="https://colab.research.google.com/github/Monika171/Deep-Learning-with-Pytorch/blob/main/intro_to_pytorch(plus_Gradient_Descent_and_Linear_Regression).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('1sJfUmMfx-lt8o_uuG63BiapOV-hiBKE7')

# Pytorch Basics: Tensors & Gradients

In [2]:
!pip install jovian --upgrade --quiet

In [3]:
import jovian

In [4]:
jovian.commit(project='pytorch-basics-dummy')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/monika171/pytorch-basics-dummy


'https://jovian.ai/monika171/pytorch-basics-dummy'

import the torch module to get started.

In [5]:
import torch

# Tensors
At its core, PyTorch is a library for processing tensors. A tensor is a number, vector, matrix, or any n-dimensional array. Let's create a tensor with a single number.

In [6]:
# Number
t1 = torch.tensor(4.)
t1

tensor(4.)

In [7]:
t1.dtype

torch.float32

In [8]:
# Vector
t2 = torch.tensor([1., 2,3,4])
t2

tensor([1., 2., 3., 4.])

In [9]:
t2.dtype

torch.float32

In [10]:
# Matrix
t3 = torch.tensor([[5.,6],
                   [7,8],
                   [9,10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [11]:
# 3-dimentional array
t4 = torch.tensor([
                   [[11,12,13], [13,14,15]],
                   [[15,16,17],[17,18,19.]]
])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [12]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [13]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [14]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [15]:
print(t4)
t4.shape

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


torch.Size([2, 2, 3])

In [16]:
# Note that it's not possible to create tensors with an improper shape.
# Matrix
# t5 = torch.tensor([[5.,6,11],
#                    [7,8],
#                    [9,10]])
# t5

A ValueError is thrown because the lengths of the rows [5., 6, 11] and [7, 8] don't match.



## Tensor operations and gradients

We can combine tensors with the usual arithmetic operations. Let's look at an example:

In [17]:
# Create tensors

x = torch.tensor(3.)
w = torch.tensor(4., requires_grad = True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

We've created three tensors: x, w, and b, all numbers. w and b have an additional parameter requires_grad set to True. <br>
Let's create a new tensor y by combining these tensors.

In [18]:
y = w * x + b
y


# dy/dw
# x + 0
# dy/dx ####
# w + 0
# dy/db
# 1



1

As expected, y is a tensor with the value 3 * 4 + 5 = 17. What makes PyTorch unique is that we can automatically compute the derivative of y w.r.t. the tensors that have requires_grad set to True i.e. w and b. This feature of PyTorch is called autograd (automatic gradients).
<br>

To compute the derivatives, we can invoke the .backward method on our result y.

In [19]:
#  Compute derivatives
y.backward()

The derivatives of y w.r.t the input tensors are stored in the .grad property of the respective tensors.

In [20]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db tensor(1.)


As expected, dy/dw has the same value as x, i.e., 3, and dy/db has the value 1. Note that x.grad is None because x doesn't have requires_grad set to True.
<br>
The "grad" in w.grad is short for gradient, which is another term for derivative. The term gradient is primarily used while dealing with vectors and matrices.
<br>
WE ARE NOT INTERESTED IN FUTURE OUTPUTS RELATED TO x , BUT WE ARE INTERESTED IN FUTURE OUTPUTS RELATED TO w and b. WOULD NOT WANT TO DO USELESS OPERATIONS

## Tensor functions
Apart from arithmetic operations, the torch module also contains many functions for creating and manipulating tensors. Let's look at some examples.

In [21]:
# Create a tensor with a fixed value for every element
t6 = torch.full((3,2), 42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [22]:
t3, t6

(tensor([[ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]), tensor([[42, 42],
         [42, 42],
         [42, 42]]))

In [23]:
# Concatenate two tensors with compatible shapes
t7 = torch.cat((t3, t6))
t7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [24]:
# Compute the sin of each element
t8 = torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [25]:
t8.shape

torch.Size([6, 2])

In [26]:
# Change the shape of a tensor
t9 = t8.reshape(3,2,2)
t9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

## Interoperability with Numpy

In [27]:
import numpy as np

x = np.array([[1,2],[3,4.]])
x

array([[1., 2.],
       [3., 4.]])

In [28]:
x.shape

(2, 2)

We can convert a Numpy array to a PyTorch tensor using torch.from_numpy.

In [29]:
# Convert the numpy array to a torch tensor
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

Let's verify that the numpy array and torch tensor have similar data types.

In [30]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

We can convert back a PyTorch tensor to a Numpy array using the .numpy method of a tensor.

In [31]:
# Convert back a torch tensor to a numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

## Introduction to Linear Regression

create a model that predicts crop yields for apples and oranges (target variables) by looking at the average temperature, rainfall, and humidity (input variables or features) in a region. Here's the training data:

In a linear regression model, each target variable is estimated to be a weighted sum of the input variables, offset by some constant, known as a bias :

yield_apple = w11 * temp + w12 * rainfall + w13 * humidity + b1

yield_orange = w21 * temp + w22 * rainfall + w23 * humidity + b2


The learning part of linear regression is to figure out a set of weights w11, w12,... w23, b1 & b2 using the training data, to make accurate predictions for new data. The learned weights will be used to predict the yields for apples and oranges in a new region using the average temperature, rainfall, and humidity for that region.

We'll train our model by adjusting the weights slightly many times to make better predictions, using an optimization technique called **gradient descent**. 

### Training data
We can represent the training data using two matrices:
`inputs` and `targets`, 

each with one row per observation, and one column per variable.

In [32]:
# Input (temp, rainfall, humidity)
inputs = np.array ([[73, 67, 43],
                    [91, 88, 64],
                    [87, 134, 58],
                    [102, 43, 37],
                    [69, 96, 70]], dtype='float32')

In [33]:
# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype = 'float32')

In [34]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


### Linear regression model from scratch

The weights and biases (w11, w12, ... w23, b1 & b2) can also be represented as matrices, initialized as random values. The first row of w and the first element of b are used to predict the first target variable, i.e., yield of apples, and similarly, the second for oranges.

In [35]:
# Weights and biases
w = torch.randn(2,3, requires_grad = True)
b = torch.randn(2, requires_grad = True)
print(w)
print(b)

tensor([[ 1.0313, -0.2991,  0.2296],
        [ 1.4000, -0.8347, -0.2090]], requires_grad=True)
tensor([0.9418, 0.2961], requires_grad=True)


torch.randn creates a tensor with the given shape, with elements picked randomly from a normal distribution with mean 0 and standard deviation 1.

**Our model is simply a function that performs a matrix multiplication of the `inputs` and the weights `w` (transposed) and adds the bias `b` (replicated for each observation).**

In [36]:
# We can define the model as follows:
def model(x):
  return x @ w.t() + b

`@` represents matrix multiplication in PyTorch, and the `.t` method returns the transpose of tensor.

The matrix obtained by passing the input data into model is a set od predictions for the target variables.

In [37]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[ 66.0576,  37.5813],
        [ 83.1611,  40.8627],
        [ 63.8975,  -1.8816],
        [101.7668,  99.4693],
        [ 59.4573,   2.1307]], grad_fn=<AddBackward0>)


Lets compare the predictions of our model with the actual targets.

In [38]:
# Compara with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


We can see a big difference between our model's predictions and the actual targets because we've initialized our model with random weights and biases. Obviously, we can't expect a randomly initialized model to just work.

### Loss function
Before we improve our model, we need a way to evaluate how well our model is performing. We can compare the model's predictions with the actual targets using the following method:

* Calculate the difference between the two matrices(preds and targets).
* Square all the elements of the difference matrix to remove negative values.
* Calculate the average of the elements in the resulting matrix.


The result is a single number, known as mean squared error(MSE).

In [39]:
# MSE loss
def mse(t1, t2):
  diff = t1 - t2
  return torch.sum(diff * diff)/diff.numel()

`torch.sum` returns the sum of all the elements in a tensor.

`.numel` method of a tensor returns the number of elements in a tensor.


Let's compute the mean squared error for the current predictions of our model.

In [40]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(5182.2197, grad_fn=<DivBackward0>)


Here is how we can interpret the result: 

On average, each element in the prediction differs from the actual target by the square root of the loss.

And that's pretty bad, considering the numbers we are trying to predict are themslves in the range 50-200.

The result is called the loss because it indicates how bad the model is at predicting the target variables.

It represents information loss in the model: the lower the loss, the better the model.

### Compute gradients

With PyTorch, we can automatically compute the gradient or derivative of the loss w.r.t the weights and biases because they have `reqires_grad` set to `True`.



In [41]:
# Compute gradients
loss.backward()

The gradients are stored in the .grad property of the respective tensors.

Note that the derivative of the loss w.r.t the weigths, matrix is itself a matrix with the same dimensions.

In [42]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[ 1.0313, -0.2991,  0.2296],
        [ 1.4000, -0.8347, -0.2090]], requires_grad=True)
tensor([[  253.7448, -1453.9634,  -544.3538],
        [-4253.1738, -6814.3096, -3787.0825]])


### Adjust weights and biases to reduce the loss
The loss is a quadratic function of our weights and biases, and our objective is to find the set of weights where the loss is the lowest. If we plot a graph of the loss w.r.t any individual weight or bias element, it will look like the figure shown below. An important insight from calculus is that the gradient indicates the rate of change of the loss, i.e., the loss function's slope w.r.t. the weights and biases.

If a gradient element is positive:

* increasing the weight element's value slightly will increase the loss
* decreasing the weight element's value slightly will decrease the loss

If a gradient element is negative:

* increasing the weight element's value slightly will decrease the loss
* decreasing the weight element's value slightly will increase the loss


The increase or decrease in the loss by changing a weight element is proportional to the gradient of the loss w.r.t. that element. This observation forms the basis of the gradient descent optimization algorithm that we'll use to improve our model (by descending along the gradient).

**We can subtract from each weight element a small quantity proportional to the derivative of the loss w.r.t. that element to reduce the loss slightly.**

In [43]:
w
w.grad

tensor([[  253.7448, -1453.9634,  -544.3538],
        [-4253.1738, -6814.3096, -3787.0825]])

In [44]:
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5

We multiply the gradients with a very small number (10^-5 in this case) to ensure that we don't modify the weights by a very large amount. We want to take a small step in the downhill direction of the gradient, not a giant leap. This number is called the learning rate of the algorithm.

We use torch.no_grad to indicate to PyTorch that we shouldn't track, calculate, or modify gradients while updating the weights and biases.

In [45]:
# Let's verify that the loss is actually lower
loss = mse(preds, targets)
print(loss)

tensor(5182.2197, grad_fn=<DivBackward0>)


We reset the gradients to zero by invoking the .zero_() method.

we need to do this because PyTorch accumulates gradients.

Otherwise, the next time we invoke .backward on the loss, the new gradient values are added to the existing gradients, which may lead to unexpected results.

In [46]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


## Train the model using gradient descent

As seen above, we reduce the loss and improve our model using the gradient descent optimization algorithm.

Thus, we can train the model using the following steps:

1. Generate predictions
2. Calculate the loss
3. Compute gradients w.r.t. the weights and biases
4. Adjust the weights by subtracting a small quantity to the gradient
5. Reset the gradients to zero

In [47]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[ 67.0806,  46.8807],
        [ 84.5581,  53.1540],
        [ 65.9408,  13.1469],
        [102.3346, 108.1395],
        [ 61.0591,  14.2586]], grad_fn=<AddBackward0>)


In [48]:
# Calculate the loss
loss = mse(preds, targets)
print(loss)

tensor(4438.3511, grad_fn=<DivBackward0>)


In [49]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[  363.3463, -1325.2712,  -467.3461],
        [-3287.9680, -5763.1865, -3141.4980]])
tensor([-5.3501e-03, -4.4884e+01])


Let's update the weights and biases using the gradients computed above.

In [50]:
# Adjust weights & reset gradients
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5
  w.grad.zero_()
  b.grad.zero_()

Let's take a look at the new weights and biases.

In [51]:
print(w)
print(b)

tensor([[ 1.0251, -0.2714,  0.2397],
        [ 1.4754, -0.7090, -0.1397]], requires_grad=True)
tensor([0.9418, 0.2971], requires_grad=True)


With the new weights and biases, the model should have a lower loss.

In [52]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(3925.2446, grad_fn=<DivBackward0>)


We have already achieved a significant reduction in the loss merely by adjusting the weights and biases slightly using gradient descent.

## Train for multiple epochs
To reduce the loss further, we can repeat the process of adjusting the weights and biases using the gradients multiple times.

Each iteration is called a epoch. Let's train the model for 100 epochs

In [53]:
# Train for 100 epochs
for i in range(100):
  preds = model(inputs)
  loss = mse(preds, targets)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

Once again, let's verify that the loss is now lower:

In [54]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(844.8543, grad_fn=<DivBackward0>)


The loss is now much lower than its initial value. Let's look at the model's predictions and compare them with the targets.

In [55]:
# Predictions
preds

tensor([[ 65.2493,  80.9810],
        [ 86.1200, 103.4146],
        [ 96.7998, 109.5608],
        [ 67.0003,  98.3067],
        [ 82.1163,  88.2029]], grad_fn=<AddBackward0>)

In [56]:
# Targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

The prsedictions are now quite close to the target variables. We can get even better results by training for a few more epochs.

## Linear regression uaing PyTorch built-ins
We've implemented linear regression & gradient descent model using some basic tensor operations.

However, since this is a common pattern in deep learning, PyTorch provides several built-in functions and classes to make it easy to create and train models with just a few lines of code.

Let's begin by importing the torch.nn package from PyTorch, which contains utility classes for building neural networks.



In [57]:
import torch.nn as nn

In [58]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [59]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

Using 15 training examples to illustrate how to work with large datasets in small batches

### Dataset and DataLoader

We'll create a TensorDataset, which allows access to rows from inputs and targets as tuples, and provides standard APIs for working with many different types of datasets in PyTorch.

In [60]:
from torch.utils.data import TensorDataset

In [61]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

The TensorDataset allows us to access a small section of the training data using the array indexing notation ([0:3] in the above code).
It returns a tuple with two elements.

The first element contains the input variables for the selected rows, and the second contains the targets.


We'll also create a Dataloader, which can split the data into batches of a predefined size while training. It also provides other utilities like shuffling and random sampling of the data.

In [62]:
from torch.utils.data import DataLoader

In [63]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

We can use the data loader in a for loop. Let's look at an example

In [64]:
for xb, yb in train_dl:
  print(xb)
  print(yb)
  break

tensor([[ 73.,  66.,  44.],
        [102.,  43.,  37.],
        [ 73.,  67.,  43.],
        [ 87., 135.,  57.],
        [101.,  44.,  37.]])
tensor([[ 57.,  69.],
        [ 22.,  37.],
        [ 56.,  70.],
        [118., 134.],
        [ 21.,  38.]])


In each iteration, the data loader returns one batch of data with the given batch size. If shuffle is set to True, it shuffles the training data before creating batches. Shuffling helps randomize the input to the optimization algorithm, leading to a faster reduction in the loss.

### nn.Linear

Instead of initilizing the weights & biases, we can define the model using the nn.Linear class from PyTorch, which does it automatically.

In [65]:
# Define model
model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.1526,  0.4248,  0.3247],
        [ 0.3281, -0.2322,  0.0748]], requires_grad=True)
Parameter containing:
tensor([ 0.2645, -0.0011], requires_grad=True)


PyTorch models also have a helpful .parameters method, which returns a list containing all the weights and bias matrices present in the model.

For our linear regression model, we have one weight matrix and one bias matrix.

In [66]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[ 0.1526,  0.4248,  0.3247],
         [ 0.3281, -0.2322,  0.0748]], requires_grad=True),
 Parameter containing:
 tensor([ 0.2645, -0.0011], requires_grad=True)]

In [67]:
# We can use the model to generate prediction in the same way as before.

preds = model(inputs)
preds

tensor([[53.8240, 11.6064],
        [72.3092, 14.2061],
        [89.2907,  1.7616],
        [46.1053, 26.2459],
        [74.2993,  5.5791],
        [53.5518, 12.1667],
        [72.2092, 14.5132],
        [89.7680,  2.1645],
        [46.3776, 25.6856],
        [74.4715,  5.3259],
        [53.7239, 11.9134],
        [72.0370, 14.7665],
        [89.3908,  1.4545],
        [45.9332, 26.4992],
        [74.5716,  5.0188]], grad_fn=<AddmmBackward>)

### Loss Function
Instead of defining a loss function manually we can use the built-in loss function mse_loss

In [68]:
# Impost nn.functional
import torch.nn.functional as F

The `nn.functional` package conatins many useful loss functions and several other utilties

In [69]:
# Define loss function
loss_fn = F.mse_loss

Let's compute the loss for the current predictions of our model.

In [70]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(4342.8770, grad_fn=<MseLossBackward>)


### Optimizer

Instead of manually manipulating the model's weight & biases using gradients, we can use the optimizer `optim.SGD`. SGD is short for "stochastic gradient descent".


The term stochastic indicates that samples are random batches instead of as a single group.

In [71]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

Note that the `model.parameters()` is passed as an argument to `optim.SGD` so that the optimizer knows which matrices should be modified during theupdate step.

Also, we can specify a learning rate that controls the amount by which the parameters are modified.

### Train the model

We are now ready to train te model. We'll follow the same process to implement gradient descent:

1. Generate predictions
2. Calculate the loss
3. Compute gradients w.r.t. the weights and biases
4. Adjust the weights by subtracting a small quantity proportional to the gradient
5. Reset the gradient to zero


The only change is that we'll work batches of data instead of processing the enitire training data in every iteration.

Let's define a utility function `fit` that trains the model for a given number of epochs.

In [72]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

Some things to note above:

* We use the data loader defined earlier to get batches of data for every iteration.

* Instead of updating parameters (weights and biases) manually, we use opt.step to perform the update and opt.zero_grad to reset the gradients to zero.

* We've also added a log statement that prints the loss from the last batch of data for every 10th epoch to track training progress. loss.item returns the actual value stored in the loss tensor.

Let's train the model for 100 epochs.

In [73]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 281.6919
Epoch [20/100], Loss: 331.7337
Epoch [30/100], Loss: 213.7315
Epoch [40/100], Loss: 228.3671
Epoch [50/100], Loss: 175.3708
Epoch [60/100], Loss: 75.4787
Epoch [70/100], Loss: 41.1921
Epoch [80/100], Loss: 18.7366
Epoch [90/100], Loss: 16.8130
Epoch [100/100], Loss: 14.9688


In [74]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 57.9193,  71.8918],
        [ 80.9903,  98.8561],
        [118.5942, 133.3154],
        [ 26.3495,  46.8974],
        [ 96.9010, 110.3035],
        [ 56.7830,  71.0012],
        [ 80.6169,  98.5819],
        [118.7967, 133.7757],
        [ 27.4859,  47.7880],
        [ 97.6641, 110.9199],
        [ 57.5460,  71.6176],
        [ 79.8539,  97.9655],
        [118.9675, 133.5896],
        [ 25.5865,  46.2810],
        [ 98.0374, 111.1941]], grad_fn=<AddmmBackward>)

In [75]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

Indeed, the predictions are quite close to our targets. We have a trained a reasonably good model to predict crop yields for apples and oranges by looking at the average temperature, rainfall, and humidity in a region. We can use it to make predictions of crop yields for new regions by passing a batch containing a single row of input.

In [76]:
model(torch.tensor([[75, 63, 44.]]))

tensor([[54.4173, 69.0239]], grad_fn=<AddmmBackward>)

The predicted yield of apples is 54.13 tons per hectare, and that of oranges is 67.87 tons per hectare.



In [78]:
jovian.commit(project='pytorch-basics-dummy')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/monika171/pytorch-basics-dummy


'https://jovian.ai/monika171/pytorch-basics-dummy'