<a href="https://colab.research.google.com/github/Monika171/Deep-Learning-with-Pytorch/blob/main/intro_to_pytorch(plus_Gradient_Descent_and_Linear_Regression).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [113]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('1sJfUmMfx-lt8o_uuG63BiapOV-hiBKE7')

# Pytorch Basics: Tensors & Gradients

In [114]:
!pip install jovian --upgrade --quiet

In [115]:
import jovian

In [116]:
jovian.commit(project='pytorch-basics-dummy')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/monika171/pytorch-basics-dummy


'https://jovian.ai/monika171/pytorch-basics-dummy'

import the torch module to get started.

In [117]:
import torch

# Tensors
At its core, PyTorch is a library for processing tensors. A tensor is a number, vector, matrix, or any n-dimensional array. Let's create a tensor with a single number.

In [118]:
# Number
t1 = torch.tensor(4.)
t1

tensor(4.)

In [119]:
t1.dtype

torch.float32

In [120]:
# Vector
t2 = torch.tensor([1., 2,3,4])
t2

tensor([1., 2., 3., 4.])

In [121]:
t2.dtype

torch.float32

In [122]:
# Matrix
t3 = torch.tensor([[5.,6],
                   [7,8],
                   [9,10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [123]:
# 3-dimentional array
t4 = torch.tensor([
                   [[11,12,13], [13,14,15]],
                   [[15,16,17],[17,18,19.]]
])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [124]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [125]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [126]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [127]:
print(t4)
t4.shape

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


torch.Size([2, 2, 3])

In [128]:
# Note that it's not possible to create tensors with an improper shape.
# Matrix
# t5 = torch.tensor([[5.,6,11],
#                    [7,8],
#                    [9,10]])
# t5

A ValueError is thrown because the lengths of the rows [5., 6, 11] and [7, 8] don't match.



## Tensor operations and gradients

We can combine tensors with the usual arithmetic operations. Let's look at an example:

In [129]:
# Create tensors

x = torch.tensor(3.)
w = torch.tensor(4., requires_grad = True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

We've created three tensors: x, w, and b, all numbers. w and b have an additional parameter requires_grad set to True. <br>
Let's create a new tensor y by combining these tensors.

In [130]:
y = w * x + b
y


# dy/dw
x + 0
# dy/dx ####
w + 0
# dy/db
1



1

As expected, y is a tensor with the value 3 * 4 + 5 = 17. What makes PyTorch unique is that we can automatically compute the derivative of y w.r.t. the tensors that have requires_grad set to True i.e. w and b. This feature of PyTorch is called autograd (automatic gradients).
<br>

To compute the derivatives, we can invoke the .backward method on our result y.

In [131]:
#  Compute derivatives
y.backward()

The derivatives of y w.r.t the input tensors are stored in the .grad property of the respective tensors.

In [132]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db tensor(1.)


As expected, dy/dw has the same value as x, i.e., 3, and dy/db has the value 1. Note that x.grad is None because x doesn't have requires_grad set to True.
<br>
The "grad" in w.grad is short for gradient, which is another term for derivative. The term gradient is primarily used while dealing with vectors and matrices.
<br>
WE ARE NOT INTERESTED IN FUTURE OUTPUTS RELATED TO x , BUT WE ARE INTERESTED IN FUTURE OUTPUTS RELATED TO w and b. WOULD NOT WANT TO DO USELESS OPERATIONS

## Tensor functions
Apart from arithmetic operations, the torch module also contains many functions for creating and manipulating tensors. Let's look at some examples.

In [133]:
# Create a tensor with a fixed value for every element
t6 = torch.full((3,2), 42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [134]:
t3, t6

(tensor([[ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]), tensor([[42, 42],
         [42, 42],
         [42, 42]]))

In [135]:
# Concatenate two tensors with compatible shapes
t7 = torch.cat((t3, t6))
t7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [136]:
# Compute the sin of each element
t8 = torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [137]:
t8.shape

torch.Size([6, 2])

In [138]:
# Change the shape of a tensor
t9 = t8.reshape(3,2,2)
t9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

## Interoperability with Numpy

In [139]:
import numpy as np

x = np.array([[1,2],[3,4.]])
x

array([[1., 2.],
       [3., 4.]])

In [140]:
x.shape

(2, 2)

We can convert a Numpy array to a PyTorch tensor using torch.from_numpy.

In [141]:
# Convert the numpy array to a torch tensor
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

Let's verify that the numpy array and torch tensor have similar data types.

In [142]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

We can convert back a PyTorch tensor to a Numpy array using the .numpy method of a tensor.

In [143]:
# Convert back a torch tensor to a numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

## Introduction to Linear Regression

create a model that predicts crop yields for apples and oranges (target variables) by looking at the average temperature, rainfall, and humidity (input variables or features) in a region. Here's the training data:

In a linear regression model, each target variable is estimated to be a weighted sum of the input variables, offset by some constant, known as a bias :

yield_apple = w11 * temp + w12 * rainfall + w13 * humidity + b1

yield_orange = w21 * temp + w22 * rainfall + w23 * humidity + b2


The learning part of linear regression is to figure out a set of weights w11, w12,... w23, b1 & b2 using the training data, to make accurate predictions for new data. The learned weights will be used to predict the yields for apples and oranges in a new region using the average temperature, rainfall, and humidity for that region.

We'll train our model by adjusting the weights slightly many times to make better predictions, using an optimization technique called **gradient descent**. 

### Training data
We can represent the training data using two matrices:
`inputs` and `targets`, 

each with one row per observation, and one column per variable.

In [144]:
# Input (temp, rainfall, humidity)
inputs = np.array ([[73, 67, 43],
                    [91, 88, 64],
                    [87, 134, 58],
                    [102, 43, 37],
                    [69, 96, 70]], dtype='float32')

In [145]:
# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype = 'float32')

In [146]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


### Linear regression model from scratch

The weights and biases (w11, w12, ... w23, b1 & b2) can also be represented as matrices, initialized as random values. The first row of w and the first element of b are used to predict the first target variable, i.e., yield of apples, and similarly, the second for oranges.

In [147]:
# Weights and biases
w = torch.randn(2,3, requires_grad = True)
b = torch.randn(2, requires_grad = True)
print(w)
print(b)

tensor([[ 0.2399,  1.3024,  0.1774],
        [-1.0240, -0.4862, -0.1072]], requires_grad=True)
tensor([-1.5371, -1.2196], requires_grad=True)


torch.randn creates a tensor with the given shape, with elements picked randomly from a normal distribution with mean 0 and standard deviation 1.

**Our model is simply a function that performs a matrix multiplication of the `inputs` and the weights `w` (transposed) and adds the bias `b` (replicated for each observation).**

In [148]:
# We can define the model as follows:
def model(x):
  return x @ w.t() + b

`@` represents matrix multiplication in PyTorch, and the `.t` method returns the transpose of tensor.

The matrix obtained by passing the input data into model is a set od predictions for the target variables.

In [149]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[ 110.8700, -113.1571],
        [ 146.2659, -144.0508],
        [ 204.1532, -161.6762],
        [  85.5049, -130.5414],
        [ 152.4717, -126.0555]], grad_fn=<AddBackward0>)


Lets compare the predictions of our model with the actual targets.

In [150]:
# Compara with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


We can see a big difference between our model's predictions and the actual targets because we've initialized our model with random weights and biases. Obviously, we can't expect a randomly initialized model to just work.

### Loss function
Before we improve our model, we need a way to evaluate how well our model is performing. We can compare the model's predictions with the actual targets using the following method:

* Calculate the difference between the two matrices(preds and targets).
* Square all the elements of the difference matrix to remove negative values.
* Calculate the average of the elements in the resulting matrix.


The result is a single number, known as mean squared error(MSE).

In [151]:
# MSE loss
def mse(t1, t2):
  diff = t1 - t2
  return torch.sum(diff * diff)/diff.numel()

`torch.sum` returns the sum of all the elements in a tensor.

`.numel` method of a tensor returns the number of elements in a tensor.


Let's compute the mean squared error for the current predictions of our model.

In [152]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(28955.4570, grad_fn=<DivBackward0>)


Here is how we can interpret the result: 

On average, each element in the prediction differs from the actual target by the square root of the loss.

And that's pretty bad, considering the numbers we are trying to predict are themslves in the range 50-200.

The result is called the loss because it indicates how bad the model is at predicting the target variables.

It represents information loss in the model: the lower the loss, the better the model.

### Compute gradients

With PyTorch, we can automatically compute the gradient or derivative of the loss w.r.t the weights and biases because they have `reqires_grad` set to `True`.



In [153]:
# Compute gradients
loss.backward()

The gradients are stored in the .grad property of the respective tensors.

Note that the derivative of the loss w.r.t the weigths, matrix is itself a matrix with the same dimensions.

In [154]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[ 0.2399,  1.3024,  0.1774],
        [-1.0240, -0.4862, -0.1072]], requires_grad=True)
tensor([[  5448.8184,   5662.0435,   3457.6038],
        [-19060.9961, -20810.4453, -12800.6289]])


### Adjust weights and biases to reduce the loss
The loss is a quadratic function of our weights and biases, and our objective is to find the set of weights where the loss is the lowest. If we plot a graph of the loss w.r.t any individual weight or bias element, it will look like the figure shown below. An important insight from calculus is that the gradient indicates the rate of change of the loss, i.e., the loss function's slope w.r.t. the weights and biases.

If a gradient element is positive:

* increasing the weight element's value slightly will increase the loss
* decreasing the weight element's value slightly will decrease the loss

If a gradient element is negative:

* increasing the weight element's value slightly will decrease the loss
* decreasing the weight element's value slightly will increase the loss


The increase or decrease in the loss by changing a weight element is proportional to the gradient of the loss w.r.t. that element. This observation forms the basis of the gradient descent optimization algorithm that we'll use to improve our model (by descending along the gradient).

We can subtract from each weight element a small quantity proportional to the derivative of the loss w.r.t. that element to reduce the loss slightly.

In [155]:
w
w.grad

tensor([[  5448.8184,   5662.0435,   3457.6038],
        [-19060.9961, -20810.4453, -12800.6289]])

In [156]:
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5

In [157]:
jovian.commit(project='pytorch-basics-dummy')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/monika171/pytorch-basics-dummy


'https://jovian.ai/monika171/pytorch-basics-dummy'